export const CreateUser = "/createuser"
export const UserLogin = "/login"
export const UserList = "/userlist"
export const MenuList = "/menulist"
export const CreateOrder = "/createorder"
export const UserOrders = "/orderlist"
export const UpdateStatus = "/orderstatus/update"
