version: "3.9"

services:
  server:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "dudelybhai"
      POSTGRES_PASSWORD: "test@123*"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
